//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job_Portal_Managment_System
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JobDBEntities : DbContext
    {
        public JobDBEntities()
            : base("name=JobDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APPLICATION> APPLICATIONS { get; set; }
        public virtual DbSet<EMPLOYER> EMPLOYERS { get; set; }
        public virtual DbSet<JOB_SEEKER_PROFILE> JOB_SEEKER_PROFILE { get; set; }
        public virtual DbSet<JOB> JOBS { get; set; }
        public virtual DbSet<NOTIFICATION> NOTIFICATIONS { get; set; }
        public virtual DbSet<SAVED_JOBS> SAVED_JOBS { get; set; }
        public virtual DbSet<Skill> Skills { get; set; }
        public virtual DbSet<USER_SKILLS> USER_SKILLS { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
    }
}
