//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job_Portal_Managment_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skill
    {
        public Skill()
        {
            this.USER_SKILLS = new HashSet<USER_SKILLS>();
        }
    
        public int skillID { get; set; }
        public string skillName { get; set; }
    
        public virtual ICollection<USER_SKILLS> USER_SKILLS { get; set; }
    }
}
